config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :cocktail, :scope => [:ingredient]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail: @cocktail)
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Dose.find(params[:id]).cocktail
    Dose.delete(params[:id])
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>
<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail|  %>
      <div class="col-xs-12 col-sm-4">
        <!-- insert <div class="card"> -->
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path cocktail.photo %>');">
            <div class="card-description">
              <h2><%= cocktail.name %></h2>
              <ul>
                <% cocktail.ingredients.each do |ingredient| %>
                  <li><%= ingredient.name %></li> 
                <% end %>
              </ul>
            </div>
            <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Add a Cocktail</h1>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit, class: "btn-danger" %>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
<h2>Ingredients</h2>
<ul>
<% @doses.each do |dose| %>
  <li><%= dose.description %> of <%= dose.ingredient.name %> <%= link_to raw('<i class="fas fa-trash-alt"></i>'), dose_path(dose), method: :delete, data: { confirm: "Are you sure you want to remove the #{dose.ingredient.name}?" } %></li>
<% end %>
</ul>
<%= link_to raw('<i class="fas fa-plus-circle"></i> add an ingredient'), new_cocktail_dose_path(@cocktail) %><br>
<br>
<p class="h4"><%= link_to raw('<i class="fas fa-arrow-left"></i> all cocktails'), cocktails_path %></p>

app/views/doses/new.html.erb
<h1>Add an Ingredient</h1>
<%= simple_form_for @dose, url: cocktail_doses_path do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit, class: "btn-danger" %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to raw('<h1><i class="fas fa-cocktail"></i><small>Cocktail Bootleggers</small></h1>'), root_path, class: "navbar-wagon-brand" %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to raw('<i class="fas fa-plus-square"></i> Add a Cocktail'), new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <%= link_to raw('<i class="fas fa-plus-square"></i>'), new_cocktail_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container cb-styling">
    <%= yield %>
    </div>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>